services:
  auth-service:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./auth-service:/app
    depends_on:
      - db-command

  command-service:
    build:
      context: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ./command-service:/app
    depends_on:
      - db-command
      - redis

  query-service:
    build:
      context: .
    ports:
      - "8002:8000"
    env_file:
      - .env
    volumes:
      - ./query-service:/app
    depends_on:
      - db-query
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - command-service
      - query-service

  db-command:
    image: postgres:14.2-alpine
    env_file:
     - .env
    volumes:
      - postgres-command-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  db-query:
    image: postgres:14.2-alpine
    env_file:
     - .env
    volumes:
      - postgres-query-data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  redis:
    image: redis:7.2.5-alpine
    ports:
      - "6379:6379"

volumes:
  postgres-command-data:
  postgres-query-data:
